# Generated by Django 5.1 on 2024-08-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race_id', models.CharField(max_length=20)),
                ('horse_name', models.CharField(max_length=255)),
                ('jockey_name', models.CharField(max_length=255)),
                ('horse_number', models.IntegerField()),
                ('runtime', models.CharField(blank=True, max_length=50, null=True)),
                ('odds', models.FloatField()),
                ('passing_order', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('weight_change', models.IntegerField()),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('weight_carry', models.FloatField()),
                ('last_3f', models.CharField(blank=True, max_length=50, null=True)),
                ('popularity', models.CharField(blank=True, max_length=50, null=True)),
                ('race_name', models.CharField(max_length=255)),
                ('race_date', models.DateField()),
                ('track', models.CharField(max_length=50)),
                ('race_class', models.CharField(max_length=50)),
                ('surface', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
                ('turn', models.CharField(max_length=50)),
                ('track_condition', models.CharField(max_length=50)),
                ('weather', models.CharField(max_length=50)),
                ('track_id', models.IntegerField()),
                ('track_name', models.CharField(max_length=50)),
            ],
        ),
    ]
