# Generated by Django 5.1 on 2024-08-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_racing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='race_date',
            field=models.DateField(null=True),
        ),
    ]
