# Generated by Django 5.1 on 2024-08-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horse_racing', '0002_alter_raceresult_race_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raceresult',
            name='odds',
            field=models.FloatField(null=True),
        ),
    ]
